# -*- coding: utf-8 -*-
"""Cópia de Aula01-Nator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zLUKSeefUMH6hEFPcrLsH4b-m_Zt9rMw
"""

for num in range(1, 201):
    if num % 2 == 0:
        print(num)