# -*- coding: utf-8 -*-
"""Git e github.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xv9bTLYuYqDPkUMGgWruFXpb7qL2yqp3
"""

notas = []
total_notas = int(input("Digite o número total de notas: "))

for i in range(total_notas):
    nota = float(input(f"Digite a nota {i+1}: "))
    notas.append(nota)

media = sum(notas) / total_notas

print("A média das notas é:", media)