# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DhOzgjMi70Ywrm0JL8RqJBxj-CRdcRux
"""

lista = [1, 2, 3, 4, 5, 6, 7]
lista_concatenada = lista + lista
print(lista_concatenada)

lista = [10,20,50,80,20,20]
soma_ultimos = sum(lista[-3:])
print(soma_ultimos)