import tkinter as tk

janela = tk.Tk()
janela.title("aula_08_tkinter")
#janela.geometry("500x300")

# Criando widgets
widget_entrada = tk.Label(janela, width=40,height=7)
widget1 = tk.Button(janela, text="7", width=15, bg='yellow')
widget2 = tk.Button(janela, text="8", width=15, bg='yellow')
widget3 = tk.Button(janela, text="9", width=15, bg='yellow')
widget4 = tk.Button(janela, text="-", width=15, bg='red')
widget5 = tk.Button(janela, text="4", width=15, bg='yellow')
widget6 = tk.Button(janela, text="5", width=15, bg='yellow')
widget7 = tk.Button(janela, text="6", width=15, bg='yellow')
widget8 = tk.Button(janela, text="+", width=15, bg='red')
widget9 = tk.Button(janela, text="1", width=15, bg='yellow')
widget10 = tk.Button(janela, text="2",width=15, bg='yellow')
widget11 = tk.Button(janela, text="3",width=15, bg='yellow')
widget12 = tk.Button(janela, text="/",width=15, bg='red')
widget13 = tk.Button(janela, text="C",width=15, bg='green')
widget14 = tk.Button(janela, text="0",width=15, bg='yellow')
widget15 = tk.Button(janela, text="=",width=15, bg='red')
widget16 = tk.Button(janela, text="*",width=15, bg='red')
widget_entrada.grid(row=0, column=0, columnspan=10)  
widget1.grid(row=2, column=1)  
widget2.grid(row=2, column=2)
widget3.grid(row=2, column=3)
widget4.grid(row=2, column=4)
widget5.grid(row=3, column=1)  
widget6.grid(row=3, column=2)
widget7.grid(row=3, column=3)
widget8.grid(row=3, column=4)
widget9.grid(row=4, column=1)  
widget10.grid(row=4, column=2)
widget11.grid(row=4, column=3)
widget12.grid(row=4, column=4)
widget13.grid(row=5, column=1)  
widget14.grid(row=5, column=2)
widget15.grid(row=5, column=3)
widget16.grid(row=5, column=4)



tk.mainloop()